#!/usr/bin/env python3
"""BP rev A1 flat schematic from tools/bp_model.py (single source with the PCB). Emitter = SM-1 build_sch style:
label on every connected pin end, no_connect on the rest. Writes MP62_BP.kicad_sym, backplane.kicad_sch, sym-lib-table."""
import os, sys, uuid
HERE = os.path.dirname(os.path.abspath(__file__)); PRJ = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, HERE)
import bp_model as M
NAME = "backplane"; LIBN = "MP62_BP"
U = lambda: str(uuid.uuid4()); ROOT = U()
SYMS = M.SYMS
def pin_geom(s):
    L = [p for p in s["pins"] if p[2] == "L"]; R = [p for p in s["pins"] if p[2] == "R"]
    n = max(len(L), len(R)); h = (n + 1) * 2.54
    w = s["w"] or max(10, 1.27 * max([len(p[1]) for p in s["pins"]] + [4]) * 2 + 2)
    w = round(w / 2.54) * 2.54
    geo = {}
    for side, lst in (("L", L), ("R", R)):
        for i, p in enumerate(lst):
            y = h / 2 - 2.54 * (i + 1); x = -w / 2 - 2.54 if side == "L" else w / 2 + 2.54
            geo[p[0]] = (round(x, 2), round(y, 2), 0 if side == "L" else 180, p[1])
    return w, h, geo
def esc(s): return str(s).replace('"', "'")
def sym_text(name, s):
    w, h, geo = pin_geom(s)
    pins = "".join(f'      (pin passive line (at {x} {y} {a}) (length 2.54) (name "{esc(nm)}" (effects (font (size 1.0 1.0)))) (number "{num}" (effects (font (size 1.0 1.0)))))\n'
                   for num, (x, y, a, nm) in geo.items())
    hide = ' (hide yes)'
    return (f'  (symbol "{name}" (pin_names (offset 0.508)) (exclude_from_sim no) (in_bom yes) (on_board yes)\n'
            f'    (property "Reference" "{s["ref"]}" (at 0 {h / 2 + 1.5:.2f} 0) (effects (font (size 1.27 1.27))))\n'
            f'    (property "Value" "{name}" (at 0 {-h / 2 - 1.5:.2f} 0) (effects (font (size 1.27 1.27))))\n'
            f'    (property "Footprint" "MP62_BP:{s["fp"].split(":")[-1]}" (at 0 0 0) (effects (font (size 1.27 1.27)){hide}))\n'
            f'    (property "Datasheet" "" (at 0 0 0) (effects (font (size 1.27 1.27)){hide}))\n'
            f'    (property "Description" "{esc(s["desc"])}" (at 0 0 0) (effects (font (size 1.27 1.27)){hide}))\n'
            f'    (symbol "{name}_0_1" (rectangle (start {-w / 2:.2f} {h / 2:.2f}) (end {w / 2:.2f} {-h / 2:.2f}) (stroke (width 0.254) (type default)) (fill (type background))))\n'
            f'    (symbol "{name}_1_1"\n{pins}    )\n  )\n')
used = sorted({p["sym"] for p in M.PARTS})
lib = '(kicad_symbol_lib (version 20241209) (generator "mp62_bp") (generator_version "9.0")\n' + "".join(sym_text(n, SYMS[n]) for n in used) + ')\n'
open(os.path.join(PRJ, LIBN + ".kicad_sym"), "w").write(lib)
# ---- placement: shelf packing on A0 (1189 x 841), big symbols first
order = sorted(M.PARTS, key=lambda p: (-pin_geom(SYMS[p["sym"]])[1], p["ref"]))
X0, Y0, XMAX = 30.0, 30.0, 1150.0
x, y, shelf = X0, Y0, 0.0
pos = {}
for p in order:
    w, h, _ = pin_geom(SYMS[p["sym"]])
    lab = 9 * 2.54   # room for labels each side
    W_ = w + 2 * lab + 5.08; H_ = h + 7.62
    if x + W_ > XMAX: x = X0; y += shelf; shelf = 0.0
    pos[p["ref"]] = (round((x + W_ / 2) / 2.54) * 2.54, round((y + H_ / 2) / 2.54) * 2.54)
    x += W_; shelf = max(shelf, H_)
paper = "A0" if y + shelf < 820 else "User 1600 1200"
out = [f'(kicad_sch (version 20250114) (generator "eeschema") (generator_version "9.0") (uuid "{ROOT}") (paper "{paper.split()[0]}"{"" if paper == "A0" else " 1600 1200"})',
       '  (title_block (title "MP62 backplane rev A1 (BP-G4 cost-down)") (date "2026-10-04") (rev "A1")'
       ' (company "MacPro6,2 / Aidan Winkler") (comment 1 "Flat sheet, label connectivity; generated by tools/build_bp_sch.py from tools/bp_model.py (same model as the PCB)")'
       ' (comment 2 "FS lanes reversed on CPU-LINK = ICD rev 3.1 proposal (needs approval). Gen5 redrivers removed: Gen4 loss budget, see docs/loss_budget_A1.md"))',
       '  (lib_symbols']
for n in used:
    out.append(sym_text(f"{LIBN}:{n}", SYMS[n]).replace(f'(symbol "{LIBN}:{n}_0_1"', f'(symbol "{n}_0_1"').replace(f'(symbol "{LIBN}:{n}_1_1"', f'(symbol "{n}_1_1"'))
out.append('  )')
nl = nnc = 0
for p in M.PARTS:
    s = SYMS[p["sym"]]; w, h, geo = pin_geom(s); X, Y = pos[p["ref"]]; dnp = p["dnp"]
    out.append(f'  (symbol (lib_id "{LIBN}:{p["sym"]}") (at {X:.3f} {Y:.3f} 0) (unit 1) (exclude_from_sim no) (in_bom {"no" if (dnp or p["ref"].startswith(("H", "JP"))) else "yes"}) (on_board yes) (dnp {"yes" if dnp else "no"}) (uuid "{U()}")')
    out.append(f'    (property "Reference" "{p["ref"]}" (at {X} {Y - h / 2 - 1.5:.2f} 0) (effects (font (size 1.27 1.27))))')
    out.append(f'    (property "Value" "{esc(p["value"])}" (at {X} {Y + h / 2 + 1.5:.2f} 0) (effects (font (size 1.27 1.27))))')
    out.append(f'    (property "Footprint" "MP62_BP:{p["fp"].split(":")[-1]}" (at {X} {Y} 0) (effects (font (size 1.27 1.27)) (hide yes)))')
    out.append(f'    (property "Datasheet" "" (at {X} {Y} 0) (effects (font (size 1.27 1.27)) (hide yes)))')
    out.append(f'    (property "LCSC" "{esc(p["lcsc"])}" (at {X} {Y} 0) (effects (font (size 1.27 1.27)) (hide yes)))')
    out.append(f'    (property "JLC_Type" "{esc(p["jlc"])}" (at {X} {Y} 0) (effects (font (size 1.27 1.27)) (hide yes)))')
    for num in geo: out.append(f'    (pin "{num}" (uuid "{U()}"))')
    out.append(f'    (instances (project "{NAME}" (path "/{ROOT}" (reference "{p["ref"]}") (unit 1))))\n  )')
    for num, (px, py, a, nm) in geo.items():
        x_, y_ = round(X + px, 3), round(Y - py, 3)
        if p["nets"].get(num):
            ang, just = (180, "right bottom") if a == 0 else (0, "left bottom")
            jj = "right" if a == 0 else "left"
            out.append(f'  (global_label "{p["nets"][num]}" (shape passive) (at {x_} {y_} {ang}) (fields_autoplaced yes) (effects (font (size 1.0 1.0)) (justify {jj})) (uuid "{U()}"))'); nl += 1
        else:
            out.append(f'  (no_connect (at {x_} {y_}) (uuid "{U()}"))'); nnc += 1
out.append('  (sheet_instances (path "/" (page "1")))\n)')
open(os.path.join(PRJ, NAME + ".kicad_sch"), "w").write("\n".join(out) + "\n")
open(os.path.join(PRJ, "sym-lib-table"), "w").write('(sym_lib_table\n  (version 7)\n  (lib (name "MP62_BP")(type "KiCad")(uri "${KIPRJMOD}/MP62_BP.kicad_sym")(options "")(descr "MP62 backplane A1 symbols"))\n)\n')
print("symbols", len(used), "parts", len(M.PARTS), "labels", nl, "no_connect", nnc, "paper", paper, "height", round(y + shelf))
