#!/usr/bin/env python3
"""MP62 CPU-LINK (hub) pinout draft for Amphenol Mini Cool Edge 224 (ME1022410103011).
Positions A1..A112 / B1..B112; 4 bays x 28 per side; A1 at the +x end of the BP footprint.
Side A row (toward disc +y) = host TX (CPU board -> BP) routed on BP L1; side B = host RX, BP L6.
Bays 1-3: GND-S-S repeating (G at k = 1,4,...,28 within each bay) => 9 diff pairs per bay side."""
import csv, collections, os
OUT = os.path.join(os.path.dirname(__file__), "..", "docs", "cpulink_224_pinout_draft.csv")
def bay_pairs(names):
    assert len(names) == 9
    pins = []
    for k in range(28):
        if k % 3 == 0: pins.append("GND")
        else:
            p = names[k // 3]
            pins.append(p + ("_P" if k % 3 == 1 else "_N") if p != "GND" else "GND")
    return pins
# Face P: lane 15 at the outer (+x) end, lane 0 innermost (order-preserving toward J9).
A = (bay_pairs(["FP_PET%d" % l for l in range(15, 6, -1)]) +
     bay_pairs(["FP_PET%d" % l for l in range(6, -1, -1)] + ["FP_REFCLK", "RSVD_REFCLK2"]) +
     bay_pairs(["FS_PET%d" % l for l in range(0, 4)] + ["FS_REFCLK", "SATA0_TX", "RSVD_HS_A1", "RSVD_HS_A2", "GND"]))
B = (bay_pairs(["FP_PER%d" % l for l in range(15, 6, -1)]) +
     bay_pairs(["FP_PER%d" % l for l in range(6, -1, -1)] + ["USB2_FACEP", "RSVD_HS_B1"]) +
     bay_pairs(["FS_PER%d" % l for l in range(0, 4)] + ["SATA0_RX", "USB2_MCU", "USB2_FACES", "USB2_SPARE", "RSVD_HS_B2"]))
lsA = ["PWRBTN#", "RSTBTN#", "SUS_S3#", "SUS_S4_S5#", "RSMRST_OUT#", "VIN_PWR_OK", "PLTRST#", "THERMTRIP#",
       "CARRIER_HOT#", "WAKE0#", "BIOS_SEL", "GPIO0", "GPIO1", "PWR_ALERT#", "5V_SBY", "5V_SBY", "5V_SBY", "5V_SBY"]
lsB = ["SMB_CLK", "SMB_DAT", "SMB_ALERT#", "I2C0_CLK", "I2C0_DAT", "UART0_TX", "UART0_RX", "FAN_PWMOUT", "FAN_TACHIN",
       "GPIO2", "GPIO3", "RSVD_LS2", "RSVD_LS3", "RSVD_LS4", "3V3_SB", "3V3_SB", "5V_SBY", "5V_SBY"]
def ls_bay(lst):
    it = iter(lst); return ["GND" if k % 3 == 0 else next(it) for k in range(28)]
A += ls_bay(lsA); B += ls_bay(lsB)
A[0] = "CC_PRSNT1#"; A[111] = "CC_PRSNT2#"      # end positions: short (last-mate) fingers on the card, tied to GND there
assert len(A) == 112 and len(B) == 112
# ICD 2026-10-02: CB (LGA1700 / Z790 + RP2350 EC) mapping of the COM-HPC-style names. dir = seen from the CB.
CB = {
    "CC_PRSNT1#": ("GND (short finger on the CB card edge)", "-"), "CC_PRSNT2#": ("GND (short finger on the CB card edge)", "-"),
    "PWRBTN#": ("EC GPIO in -> EC drives PCH PWRBTN# (BP MCU relays IOB PWRBTN_IN_N)", "in, OD, BP pull-up 3V3_SB"),
    "RSTBTN#": ("EC GPIO in -> PCH SYS_RESET#", "in, OD"),
    "SUS_S3#": ("PCH SLP_S3# (buffered, 3V3_SB)", "out"), "SUS_S4_S5#": ("PCH SLP_S4# (buffered; SLP_S5# not exported)", "out"),
    "RSMRST_OUT#": ("copy of EC-driven PCH RSMRST#", "out"), "VIN_PWR_OK": ("EC GPIO in: BP 12 V main good (PSU PWR_OK AND interlock)", "in"),
    "PLTRST#": ("PCH PLTRST# (buffered); BP makes PERST#_FP/FS = PLTRST# AND FACE_x_RDY", "out"),
    "THERMTRIP#": ("CPU/PCH THERMTRIP# (OD, wired-OR on the CB)", "out, OD"),
    "CARRIER_HOT#": ("EC GPIO in -> CPU PROCHOT# (OD)", "in, OD"), "WAKE0#": ("PCH WAKE# (faces' WAKE# ORed on the BP)", "in, OD"),
    "PWR_ALERT#": ("CB 12 V power alert (ICD rev 2, live power target): wired-OR of CB INA228 U15 ALERT (0x45 on I2C0) and U11 eFuse FLT#; BP 10k pull-up to 3V3_SB, BP MCU IRQ", "out, OD"),
    "BIOS_SEL": ("EC GPIO in (optional dual-image select)", "in"), "GPIO0": ("EC GPIO spare", "bi"), "GPIO1": ("EC GPIO spare", "bi"),
    "GPIO2": ("EC GPIO spare", "bi"), "GPIO3": ("EC GPIO spare", "bi"),
    "SMB_CLK": ("PCH SMBus (DIMM SPD/PMIC/TS bus): 0R DNP isolation on the CB by default (avoid multi-master on the DIMM bus) [Proposal]", "bi, OD"),
    "SMB_DAT": ("PCH SMBus, as SMB_CLK", "bi, OD"), "SMB_ALERT#": ("PCH SMBALERT# (DNP with SMB_*)", "bi, OD"),
    "I2C0_CLK": ("CB ID EEPROM 0x57 + EC I2C target (3V3_SB domain); BP MCU is controller", "bi, OD"), "I2C0_DAT": ("as I2C0_CLK", "bi, OD"),
    "UART0_TX": ("EC UART TX (EC <-> BP MCU)", "out"), "UART0_RX": ("EC UART RX", "in"),
    "FAN_PWMOUT": ("EC PWM out = fan demand (BP MCU writes the IOB EMC2101)", "out"), "FAN_TACHIN": ("EC capture in: tach regenerated by the BP MCU", "in"),
    "5V_SBY": ("CB standby input (PCH DSW/primary wells via bucks, EC, RTC)", "in, power"), "3V3_SB": ("CB 3V3_SB input (EC, ID EEPROM)", "in, power"),
    "USB2_MCU": ("PCH USB2 port (BP MCU, number TBD)", "bi"), "USB2_FACEP": ("PCH USB2 port -> Face P AUX 13/14", "bi"),
    "USB2_FACES": ("PCH USB2 port -> Face S AUX 13/14", "bi"), "USB2_SPARE": ("PCH USB2 port -> BP J6 13/14 -> IOB USB2_LINK (hub H2: USB-A A1-A4 + Bluetooth)", "bi"),
    "SATA0_TX": ("PCH SATA0 TX (SATA-capable HSIO not used by M.2 RP9-12; lane TBD), AC caps on the CB", "out"), "SATA0_RX": ("PCH SATA0 RX", "in"),
    "FP_REFCLK": ("PCH CLKOUT for CPU PEG (SRCn TBD; SRC11/SRC12 are taken by the IOB i226 links)", "out"),
    "FS_REFCLK": ("PCH CLKOUT for the CPU x4 port (SRCn TBD)", "out"),
}
def cbmap(sig):
    base = sig[:-2] if sig.endswith(("_P", "_N")) else sig
    if base.startswith("FP_PET"): return ("CPU PEG TX lane %s (x16 -> Face P), AC caps on the CB" % base[6:], "out")
    if base.startswith("FP_PER"): return ("CPU PEG RX lane %s" % base[6:], "in")
    if base.startswith("FS_PET"): return ("CPU PCIe x4 TX lane %s (-> Face S), AC caps on the CB" % base[6:], "out")
    if base.startswith("FS_PER"): return ("CPU PCIe x4 RX lane %s" % base[6:], "in")
    if base == "GND": return ("GND", "-")
    if base.startswith("RSVD"): return ("reserved, NC on the CB", "-")
    return CB.get(base, ("TBD", "?"))
rows = []
for i in range(112):
    bay = i // 28 + 1
    rows.append(("A%d" % (i + 1), bay, A[i]) + cbmap(A[i])); rows.append(("B%d" % (i + 1), bay, B[i]) + cbmap(B[i]))
assert not [r for r in rows if r[3] == "TBD"], [r for r in rows if r[3] == "TBD"]
with open(OUT, "w", newline="") as f:
    w = csv.writer(f); w.writerow(["pin", "bay", "signal", "cb_net (LGA1700/Z790 CB)", "dir_cb_view"]); w.writerows(rows)
cnt = collections.Counter()
for _, _, s, *_ in rows:
    if s == "GND": cnt["GND"] += 1
    elif s.startswith(("FP_PE", "FS_PE")): cnt["PCIe lane pins"] += 1
    elif "REFCLK" in s and not s.startswith("RSVD"): cnt["REFCLK pins"] += 1
    elif s.startswith("SATA"): cnt["SATA pins"] += 1
    elif s.startswith("USB2"): cnt["USB2 pins"] += 1
    elif s.startswith("RSVD"): cnt["reserved pins"] += 1
    elif s in ("5V_SBY", "3V3_SB"): cnt[s] += 1
    else: cnt["low-speed/sideband"] += 1
print(dict(cnt), sum(cnt.values()))
