M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-10-08T18:28:33-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-08T18:28:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X26.677Y20.525
X36.0Y56.5
X60.0Y56.5
X67.322Y20.525
T2
X56.0Y56.5
X80.0Y56.5
M30
